paths:
  static: public
  uploads: public/uploads

timezone: Europe/Berlin

markdown:
  engine: commonmark
  options:
    gfm: true

collections_config:
  blog:
    path: src/content/blog
    name: Blog
    icon: article
    url: '/blog/[slug]/'
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    add_options:
      - name: Neuer Blogbeitrag
    sort:
      key: pubDate
      order: desc

  team:
    path: src/content/team
    name: Team
    icon: people
    create:
      path: '[relative_base_path]/{name|slugify}.md'
    add_options:
      - name: Neues Teammitglied
    sort:
      key: order
      order: asc

  pages:
    path: src/content/pages
    name: Seiten
    icon: description
    url: '/[slug]/'
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    add_options:
      - name: Neue Seite

collection_groups:
  - heading: Inhalte
    collections:
      - blog
      - team
      - pages

_inputs:
  pubDate:
    type: date
  updatedDate:
    type: date
  heroImage:
    type: image
  photo:
    type: image
  draft:
    type: switch
  tags:
    type: array
